Numpy 是(Numerical python的简称)是一个高性能科学计算和数据分析的基础包，也是许多高级数据分析工具的基础
其部分功能如下：
- ndarray，一个具有复杂运算和复杂广播功能的快速且节约空间的多维数组。
- 对组进行快速运算的标准函数
- 读写磁盘的工具，及操作内存映射文件的工具
- 线性代数，随机数生成及傅立叶变换功能
- 集成c，c++，Fortran等语言编写的代码工具

### 1.创建ndarray

In [1]:
import numpy as np
from numpy.random import randn

data1 = [1,2,3,4,5.,4.5,3,1,0,9]
arr1 = np.array(data1)
arr1

array([1. , 2. , 3. , 4. , 5. , 4.5, 3. , 1. , 0. , 9. ])

In [2]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr2*arr2 


array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [4]:
arr2-arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])


### 2.基本的索引和切片

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[5]

5

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])
print(arr2d[2][2])
arr2d

[7 8 9]
9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2,1:]

### 3.布尔型索引

In [23]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = randn(7,4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [22]:
data

array([[ 0.89835639,  0.29486428,  0.93626375, -1.78100625],
       [ 1.65451958,  0.51978289,  0.52998961,  1.47620283],
       [-0.13289002, -0.05943526, -0.48967447, -0.07347328],
       [ 1.02977566, -0.87589384, -0.47541678, -0.2508912 ],
       [ 0.53058676,  0.18252723, -0.05807666, -0.53978103],
       [ 0.3740394 , -0.09565395,  1.47358284, -0.22274274],
       [-1.25951613,  2.55362891,  0.11479606,  1.03555821]])

In [24]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [25]:
data[names == 'Bob']

array([[ 0.37804049,  0.69738911, -0.33704937,  0.23164668],
       [-0.59321812, -0.48260372, -0.34819442,  0.52969648]])

In [26]:
data[names == 'Bob',2:]

array([[-0.33704937,  0.23164668],
       [-0.34819442,  0.52969648]])

### 4.花式索引

In [6]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [7]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [8]:
arr[[-3,-5,-7]]  #负号的索引从后开始选取行

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [12]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [13]:
arr[[1,5,7,2],[0,3,1,2]]   #坐标式选取

array([ 4, 23, 29, 10])

In [14]:
arr[[1,5,7,2]][:,[0,3,1,2]]  #先选维度，后排序

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [15]:
arr[np.ix_([1,5,7,2],[0,3,1,2])] #np.ix_函数将坐标选取转化为区域选取

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 5.数轴转置和轴对换

In [20]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
arr.T   # 数轴转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [18]:
np.dot(arr.T,arr)  # 用np.dot 计算矩阵内积

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [22]:
# 关于transpose 方法，第一次见有点难以理解
arr = np.arange(16).reshape((2,2,4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
# 这是一个2*2*4的数组 ，坐标依次是（0,0,0），（0,0,1），（0,0,2）...(1,1,3)
arr.transpose((1,0,2))

#transpose 需要传入一个元组，元组各数字代表坐标的索引，（2,2,4）->（0,1,2）
#上式(1,0,2)意思是将 1,2维的坐标对换(即  将(0,1,2）->(0,1,2))          （例 数字11的原坐标是（1,0,3）-> (0,1,3)）

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [25]:
# 相关的还有 swapaxes

arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [26]:
#上式等同于transpose(0,2,1)
arr.transpose(0,2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

swapaxes 跟 transpose 本质都是将索引对调

### 6.元素级数组函数
- abs , fabs 
- sqrt
- squre
- exp
- log , log10 ....
- sign           符号函数 1(正数)，0(零)，-1(负数)
- ceil            计算ceiling值
- floor           计算floor值
- rint            四色五入到最近整数
- modf            将数的整数和小数部分 分成两个数组返回
- isnan           返回一个 “哪些是NaN值”的布尔型的数组
- isfinite ,isinf 返回一个“哪些值是有穷”或 “哪些值是无穷”的布尔型数组
- cos,cosh,sin,sinh,tan,tanh   普通型和双曲型的三角函数