Numpy 是(Numerical python的简称)是一个高性能科学计算和数据分析的基础包，也是许多高级数据分析工具的基础
其部分功能如下：
- ndarray，一个具有复杂运算和复杂广播功能的快速且节约空间的多维数组。
- 对组进行快速运算的标准函数
- 读写磁盘的工具，及操作内存映射文件的工具
- 线性代数，随机数生成及傅立叶变换功能
- 集成c，c++，Fortran等语言编写的代码工具

1.创建ndarray

In [17]:
import numpy as np
from numpy.random import randn

data1 = [1,2,3,4,5.,4.5,3,1,0,9]
arr1 = np.array(data1)
arr1

array([1. , 2. , 3. , 4. , 5. , 4.5, 3. , 1. , 0. , 9. ])

In [4]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2*arr2 


array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [6]:
arr2-arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])


2.基本的索引和切片

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[5]

5

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])
print(arr2d[2][2])
arr2d

[7 8 9]
9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2,1:]

3.布尔型索引

In [23]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = randn(7,4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [22]:
data

array([[ 0.89835639,  0.29486428,  0.93626375, -1.78100625],
       [ 1.65451958,  0.51978289,  0.52998961,  1.47620283],
       [-0.13289002, -0.05943526, -0.48967447, -0.07347328],
       [ 1.02977566, -0.87589384, -0.47541678, -0.2508912 ],
       [ 0.53058676,  0.18252723, -0.05807666, -0.53978103],
       [ 0.3740394 , -0.09565395,  1.47358284, -0.22274274],
       [-1.25951613,  2.55362891,  0.11479606,  1.03555821]])

In [24]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [25]:
data[names == 'Bob']

array([[ 0.37804049,  0.69738911, -0.33704937,  0.23164668],
       [-0.59321812, -0.48260372, -0.34819442,  0.52969648]])

In [26]:
data[names == 'Bob',2:]

array([[-0.33704937,  0.23164668],
       [-0.34819442,  0.52969648]])

4.花式索引

In [27]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])